# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jin/dev/oclb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jin/dev/oclb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jin/dev/oclb/CMakeFiles /home/jin/dev/oclb/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jin/dev/oclb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BufferBandwidth

# Build rule for target.
BufferBandwidth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BufferBandwidth
.PHONY : BufferBandwidth

# fast build rule for target.
BufferBandwidth/fast:
	$(MAKE) -f BufferBandwidth/CMakeFiles/BufferBandwidth.dir/build.make BufferBandwidth/CMakeFiles/BufferBandwidth.dir/build
.PHONY : BufferBandwidth/fast

#=============================================================================
# Target rules for targets named ConstantBandwidth

# Build rule for target.
ConstantBandwidth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ConstantBandwidth
.PHONY : ConstantBandwidth

# fast build rule for target.
ConstantBandwidth/fast:
	$(MAKE) -f ConstantBandwidth/CMakeFiles/ConstantBandwidth.dir/build.make ConstantBandwidth/CMakeFiles/ConstantBandwidth.dir/build
.PHONY : ConstantBandwidth/fast

#=============================================================================
# Target rules for targets named GlobalMemoryBandwidth

# Build rule for target.
GlobalMemoryBandwidth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GlobalMemoryBandwidth
.PHONY : GlobalMemoryBandwidth

# fast build rule for target.
GlobalMemoryBandwidth/fast:
	$(MAKE) -f GlobalMemoryBandwidth/CMakeFiles/GlobalMemoryBandwidth.dir/build.make GlobalMemoryBandwidth/CMakeFiles/GlobalMemoryBandwidth.dir/build
.PHONY : GlobalMemoryBandwidth/fast

#=============================================================================
# Target rules for targets named LDSBandwidth

# Build rule for target.
LDSBandwidth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LDSBandwidth
.PHONY : LDSBandwidth

# fast build rule for target.
LDSBandwidth/fast:
	$(MAKE) -f LDSBandwidth/CMakeFiles/LDSBandwidth.dir/build.make LDSBandwidth/CMakeFiles/LDSBandwidth.dir/build
.PHONY : LDSBandwidth/fast

#=============================================================================
# Target rules for targets named MemoryOptimizations

# Build rule for target.
MemoryOptimizations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MemoryOptimizations
.PHONY : MemoryOptimizations

# fast build rule for target.
MemoryOptimizations/fast:
	$(MAKE) -f MemoryOptimizations/CMakeFiles/MemoryOptimizations.dir/build.make MemoryOptimizations/CMakeFiles/MemoryOptimizations.dir/build
.PHONY : MemoryOptimizations/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BufferBandwidth"
	@echo "... ConstantBandwidth"
	@echo "... GlobalMemoryBandwidth"
	@echo "... LDSBandwidth"
	@echo "... MemoryOptimizations"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

